name: aplicaciones_foliares
description: "Agrosoft llevamos soluciones integrales"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1
environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.17.2
  intl: ^0.20.3
  sqflite: ^2.4.2+1
  path: ^1.9.1
  path_provider: ^2.1.6
  device_info_plus: ^13.2.0
  pdf: ^3.12.0
  excel: ^4.0.6
  geolocator: ^14.0.3
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  maps_toolkit: ^3.1.0
  workmanager: ^0.10.9
  mobile_scanner: ^7.4.0
  share_plus: ^13.3.0    # Compartir el Excel nativamente sin renegar con permisos
  msix: ^3.18.0
  shared_preferences: ^2.5.5
  image_picker: ^1.2.3
  google_maps_flutter: ^2.18.0
  sqflite_common_ffi_web: ^1.1.1
  printing: ^5.14.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "logo/logo.png"
  adaptive_icon_background: "#F4F5F7"
  adaptive_icon_foreground: "logo/logo.png"
  
flutter:
  uses-material-design: true

  # 💡 ACA ES LO NUEVO: Inclusión de la carpeta del logo
  assets:
    - logo/logo.png
    - logo/logo_anibal.png